-- STAGING ONLY. This creates an empty quote schema; it copies no production rows.
begin;
create table public.quotes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text,
  phone text,
  email text,
  service text,
  message text,
  city text,
  product text,
  door_type text,
  glass_type text,
  hardware_finish text,
  handle_style text,
  quantity integer,
  width numeric,
  height numeric,
  square_feet numeric,
  status text default 'New',
  estimated_price numeric,
  final_price numeric,
  estimated_price_low numeric,
  estimated_price_high numeric,
  photo_paths text[]
);

alter table public.quotes enable row level security;
revoke all on public.quotes from public, anon, authenticated;
grant select, update on public.quotes to authenticated;
grant usage, select on sequence public.quotes_id_seq to authenticated;

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('quote-photos','quote-photos',false,52428800,
  array['image/jpeg','image/png','image/webp','video/mp4','video/webm','video/quicktime'])
on conflict (id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
commit;
